routes/web.php
<?php

use App\Http\Controllers\AjaxController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CandidateController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PanelController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::controller(AuthController::class)->group(function () {
    Route::any('login/{socialite?}', 'login')->name('login');
    Route::any('auth/{platform}-callback', 'authCallback')->name('auth.callback')->whereIn('socialite', ['google', 'facebook']);
    Route::any('auth/{platform}', 'authCall')->name('auth')->whereIn('socialite', ['google', 'facebook']);
    Route::any('register{company?}', 'register')->name('register', "[\w'-]+");
    Route::any('register/branch', 'branchAssign')->name('branch.assign');
    Route::any('recover', 'recover')->name('recover');
    Route::any('verify/{code?}', 'verify')->name('verify');
    Route::any('logout', 'logout')->name('logout');
});

Route::name('panel.')->middleware('access')->group(function () {
    Route::controller(PanelController::class)->group(function(){
        Route::get('/', 'home')->name('home');
        Route::get('profile', 'profile')->name('profile');
        Route::any('profile/modify', 'profileModify')->name('profile.modify');
        Route::any('profile/change-password', 'changePassword')->name('profile.change-password');
        Route::any('profile/branch', 'myBranch')->name('profile.branch');
        Route::any('job-preference', 'jobPreference')->name('jop-preference');
        Route::any('setting', 'setting')->name('setting');
    });
    Route::prefix('job')->name('job.')->controller(JobController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('import', 'import')->name('import');
        Route::any('saved', 'saved')->name('saved');
        Route::any('applied', 'applied')->name('applied');
        Route::get('{code}/apply', 'apply')->name('apply');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
        Route::get('{code}', 'show')->name('show');
    });
    Route::prefix('category')->name('category.')->controller(CategoryController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
        Route::get('{code}', 'show')->name('show');
    });
    Route::prefix('employee')->name('company.')->controller(CompanyController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::any('branch/{code}', 'branch')->name('branch');
        Route::delete('branch/{code}/delete', 'branchDelete')->name('branch.delete');
        Route::any('invite/{code?}', 'invite')->name('invite');
        Route::delete('delete/{code}', 'destroy')->name('delete');
    });
    Route::prefix('candidate')->name('candidate.')->controller(CandidateController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
    });
});


Route::prefix('ajax')->name('ajax.')->middleware('access')->controller(AjaxController::class)->group(function () {
    Route::get('job/{code}/save', 'saveJob')->name('job.save');
    Route::get('job/{code}', 'jobInfo')->name('job');
    Route::get('country/{code}/branches', 'branches')->name('branches');
    Route::get('category/{code}/sub', 'categorySub')->name('subscategories');
});

Route::get('cmd/pa-{command}', function($command){
    try {
        \Illuminate\Support\Facades\Artisan::call($command);
    } catch (Exception $e){
        dump($e);
    }
    return redirect()->route('panel.dashboard')->with('success', 'Php artisan '.$command);
});

app/Models/Job.php
<?php

namespace App\Models;

use App\Models\Scopes\MyJobs;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Job extends Model
{
    use HasFactory,SoftDeletes;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model['code'] = uniqid();
            $model['post_date'] = $model->post_date??Carbon::now();
        });
    }

    protected static function booted(): void
    {
        static::addGlobalScope(new MyJobs);
    }

    public function getIsSavedAttribute(){
        if(auth()->user()->type != 'candidate')
            return false;
        $myJob = CandidateJob::where('candidate_id', Auth::id())->where('job_id', $this->id)->first();
        return ($myJob && !null == $myJob->saved_at)?true:false;
    }
    public function getIsAppliedAttribute(){
        if(auth()->user()->type != 'candidate')
            return false;
        $myJob = CandidateJob::where('candidate_id', Auth::id())->where('job_id', $this->id)->first();
        return ($myJob && !null == $myJob->applied_at)?true:false;
    }

    public function company(){
        return $this->belongsTo(Company::class, 'company_id', 'id');
    }

    public function branch(){
        return $this->belongsTo(Branch::class, 'branch_id', 'id');
    }

    public function category(){
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function subcategory(){
        return $this->belongsTo(Category::class, 'subcategory_id', 'id')->whereNotNull('parent_id');
    }
}

app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Models\Branch;
use App\Models\CandidateJob;
use App\Models\Category;
use App\Models\Company;
use App\Models\Job;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\View;

class JobController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        View::share('title', 'Job list');
        $jobs = Job::query();
        if($request->company_id)
            $jobs->where('company_id', $request->company_id);
        if($request->branch_id)
            $jobs->where('branch_id', $request->branch_id);
        if($request->category_id)
            $jobs->where('category_id', $request->category_id);
        if($request->subcategory_id)
            $jobs->where('subcategory_id', $request->subcategory_id);

        $jobs = $jobs->orderBy('id', 'desc')->paginate(20);
        return view('back.job.list', compact('jobs'));
    }

    public function entity(Request $request, $code = null)
    {
        $my = Auth::user();
        if(!$my)
            return back()->withErrors('User type not correct.');

        if ($request->method() == 'POST' && $code) {
            $job = Job::firstWhere('code', $code);
            if (!$job)
                return back()->withInput()->withErrors('Job informaiton not found to update.');

            $request->validate([
                'title' => 'string|unique:jobs,title,'.$job->id
            ]);

            $data['title'] = $request->title;
            $data['subtitle'] = $request->subtitle;
            $data['company_id'] = $this->company($request->company_id, $request->company_url);
            $data['branch_id'] = $this->branch($request->branch_id, $data['company_id']);
            $data['category_id'] = $this->categoryPrepare($request->category_id);
            $data['subcategory_id'] = $this->subcategoryPrepare($request->subcategory_id, $data['category_id']);
            $data['info_url'] = $request->job_url;
            $data['type'] = $request->job_type;
            $data['salary_estimate'] = $request->salary_estimate;
            $data['shift'] = $request->shift;
            $data['benefit'] = $request->benefits;
            $data['description'] = $request->details;

            try {
                $job->update($data);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withErrors('Job information can not update.');
            }
            return back()->with('success', 'Job information updated successfully.');
        } elseif ($request->method() == 'POST') {

            $request->validate([
                'title' => 'string|unique:jobs'
            ]);

            $data['title'] = $request->title;
            $data['subtitle'] = $request->subtitle;
            $data['company_id'] = $this->company($request->company_id, $request->company_url);
            $data['branch_id'] = $this->branch($request->branch_id, $data['company_id']);
            $data['category_id'] = $this->categoryPrepare($request->category_id);
            $data['subcategory_id'] = $this->subcategoryPrepare($request->subcategory_id, $data['category_id']);
            $data['info_url'] = $request->job_url;
            $data['type'] = $request->job_type;
            $data['salary_estimate'] = $request->salary_estimate;
            $data['shift'] = $request->shift;
            $data['benefit'] = $request->benefits;
            $data['description'] = $request->details;

            try {
                Job::create($data);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withErrors('Job information can not submit.');
            }

            return back()->with('success', 'Sub information successfully submitted');
        } else {
            View::share('title', $code ? 'Edit job information' : 'Add new job');
            $job = Job::where('code', $code)->first();
            $companies = Company::query()->get();
            if($companies->count() == 1)
                View::share('branches', Branch::whereIn('company_id', $companies->pluck('id'))->get(['id', 'code', 'location']));
            $categories = Category::whereNull('parent_id')->get();
            if($job){
                View::share('branches', Branch::where('company_id', $job->company_id)->get(['id', 'location']));
                View::share('subcategories', Category::where('parent_id', $job->category_id)->get(['id', 'parent_id', 'name']));
            }

            return view('back.job.form', compact('job', 'companies', 'categories'));
        }
    }

    public function import(Request $request)
    {
        if ($request->method() == 'POST') {
            $request->validate([
                'document' => 'required|mimes:csv,txt'
            ]);

            $file = $request->file('document');
            $fileContents = file($file->getPathname());

            $fileHeader = ['created_at', 'title', 'job_url', 'subtitle', 'branch', 'company', 'company_url', 'review', 'description', 'type', 'salary', 'shift', 'benefit', 'category', 'subcategory', 'expire_at'];
            $tableHeader = ["\u{FEFF}Job Posted Date", "Job Title", "Job URL", "Job Subtitle", "Job Location", "Company Name", "Company URL", "Company Review Count", "Job Description", "Job Type", "Salary Estimate", "Job Shift", "Job Benefits", "Category Name", "Sub Category", "Last date of apply"];
            $requiredField = ['title', 'job_url', 'subtitle', 'description', 'company'];

            $imported = 0;
            foreach ($fileContents as $index => $line) {
                if ($index == 0) {
                    if (empty(array_diff(array_values(str_getcsv($line)), array_values($tableHeader))) && empty(array_diff(array_values($tableHeader), array_values(str_getcsv($line))))) {
                        continue;
                    } else {
                        return back()->withErrors('File is not properly formatted. Download sample file, fill-up content and try again.');
                    }
                } else {
                    $row = str_getcsv($line);
                    foreach ($fileHeader as $index => $key) {
                        $collection[$key] = $row[$index] ?? null;
                    }

                    $skip = false;
                    foreach($requiredField as $field){
                        if(null == $collection[$field] &&  empty($collection[$field])){
                            $skip = true;
                            break;
                        }
                    }
                    if($skip)
                        continue;

                    $data['title'] = $collection['title'];
                    $data['subtitle'] = $collection['subtitle'];
                    $data['info_url'] = $collection['job_url'];
                    $data['company_id'] = $collection['company'] ? $this->company($collection['company'], $collection['company_url'], $collection['review']) : null;
                    $data['branch_id'] = $collection['branch'] ? $this->branch($collection['branch'], $data['company_id']) : null;
                    $data['description'] = $collection['description'];
                    $data['type'] = $collection['type'];
                    $data['salary_estimate'] = $collection['salary'];
                    $data['shift'] = $collection['shift'];
                    $data['benefit'] = $collection['benefit'];
                    $data['category_id'] = $collection['category'] ? $this->categoryPrepare($collection['category']) : null;
                    $data['subcategory_id'] = $collection['subcategory'] ? $this->categoryPrepare($collection['subcategory'], $data['category_id']) : null;
                    $data['expire_at'] = $collection['expire_at']?$this->dateFormatter($collection['expire_at']) : Carbon::now()->addMonth();
                    $data['created_at'] = $this->dateFormatter($collection['created_at']) ?? Carbon::now();

                    try {
                        Job::create($data);
                    } catch (\PDOException $e) {
                        if (config('app.debug'))
                            dd($e->getMessage());
                        Log::error($e);
                        continue;
                    }
                    $imported += 1;
                }
            }
            return redirect()->route('panel.job.list')->with('success', $imported.' job is imported from CSV');
        } else {
            View::share('title', 'Import jobs from CSV');
            $companies = Company::all();
            $categories = Category::parentOnly()->get();
            return view('back.job.import', compact('companies', 'categories'));
        }
    }

    protected function dateFormatter($input)
    {
        if (str_contains($input, 'ago')) {
            $now = Carbon::now();
            return $now->copy()->sub(Carbon::parse($input)->diffInSeconds());
        } else {
            try {
                $carbonDate = Carbon::createFromFormat('n/j/y', $input);
            } catch (\Exception $e) {
                return false;
            }
            if ($carbonDate instanceof Carbon)
                return $carbonDate;
            else
                return false;
        }
    }


    protected function company($name, $url = null, $review = null)
    {
        if(is_numeric($name))
            return $name;

        $search['name'] = $name;

        $data['info_url'] = $url;
        $data['review'] = (int) $review;

        try {
            $company = Company::firstOrCreate($search, $data);
        } catch (\PDOException $e) {
            if (config('app.debug'))

resources/views/back/job/import.blade.php
@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4 flex-wrap">
        <h3 class="me-auto">{{ $title??'Import Job from CSV' }}</h3>
        <div>
            <a href="{{ route('panel.job.entity') }}" class="btn btn-primary btn-xs me-3"><i
                    class="fas fa-plus me-2"></i>Add New Job</a>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                {{ html()->form('POST', route('panel.job.import'))->acceptsFiles()->open() }}
                <div class="card-header text-center">
                    <h4 style="width: 100%">Upload your file</h4>
                </div>
                <div class="card-body text-center">
                    <p>Download the {{ html()->a(asset('Sample.csv'), 'Sample')->class('badge badge-info badge-xs')->attribute('download', 'Sample_Importer_'.\Carbon\Carbon::now()->timestamp.'.csv') }} file. Populate your data following the format.

                    <div class="row justify-content-center">
                        <div class="col-sm-12 col-md-10 col-lg-8">
                            {{ html()->label('Select CSV file', 'document')->class('form-label fw-bold fs-30') }}
                            {{ html()->file('document')->class('form-control')->accept('.csv')->required() }}
                        </div>
                    </div>
                </div>
                <div class="card-footer text-center">
                    {{ html()->submit('Import Jobs')->class('btn btn-primary') }}
                </div>
                {{ html()->form()->close() }}
            </div>
        </div>
        <div class="col-sm-6">
            <div class="card">
                <div class="card-header text-center">
                    <h4 style="width: 100%">Instruction</h4>
                </div>
                <div class="card-body">
                    <div class="custom-tab-1">
                        <ul class="nav nav-tabs">
                            <li class="nav-item">
                                <a class="nav-link active" data-bs-toggle="tab" href="#prepare"> Prepare file</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-bs-toggle="tab" href="#company"> Company</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-bs-toggle="tab" href="#category"> Category</a>
                            </li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="prepare" role="tabpanel">
                                <div class="pt-4">
                                    <p>To prepare file we recommend to download the sample file each time and fill up data.</p>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="company">
                                <div class="pt-4">
                                    <table style="width: 100%; color: black">
                                        <thead>
                                        <tr class="text-start">
                                            <th class="border-bottom">Company</th>
                                            <th class="border-bottom">Location</th>
                                        </tr>
                                        </thead>
                                        <tbody class="text-start">
                                        @forelse($companies??[] as $company)
                                            <tr>
                                                <td colspan="2" class="text-start">{{ $company->name }}</td>
                                            </tr>
                                            @foreach($company->branches??[] as $branch)
                                                <tr>
                                                    <td></td>
                                                    <td>{{ $branch->location }}</td>
                                                </tr>
                                            @endforeach
                                        @empty
                                            <tr>
                                                <td colspan="100%">
                                                    <p>No company found</p>
                                                    {{ html()->a(route('panel.company.entity'), 'Add new Company')->class('btn btn-outline-primary btn-xs')->target('blank') }}
                                                </td>
                                            </tr>
                                        @endforelse
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="category">
                                <div class="pt-4">
                                    <h5>All the listed categories and subcategories</h5>
                                    <ul>
                                        @forelse($categories??[] as $category)
                                            @if($category->children->count()??0)
                                                <li>
                                                    <p class="m-0">{{ $category->name }}</p>
                                                    <ul style="margin-left: 20px">
                                                        @foreach($category->children as $child)
                                                            <li>{{ $child->name }}</li>
                                                        @endforeach
                                                    </ul>
                                                </li>
                                            @else
                                                <li>{{ $category->name }}</li>
                                            @endif
                                        @empty
                                            <p>No category found</p>
                                            {{ html()->a(route('panel.category.entity'), 'Add new Category')->class('btn btn-outline-primary btn-xs')->target('blank') }}
                                        @endforelse
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>
@endsection

@push('script') @endpush

resources/views/back/job/list.blade.php
@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4 flex-wrap">
        <h3 class="me-auto">Job List</h3>
        @if(in_array(auth()->user()->type, ['admin', 'employer']))
            <div>
                <a href="{{ route('panel.job.entity') }}" class="btn btn-primary btn-xs me-3">
                    <i class="fas fa-plus me-2"></i>Add New Job</a>
                <a href="{{ route('panel.job.import') }}" class="btn btn-primary btn-xs me-3">
                    <i class="fas fa-file-lines me-2"></i>Import Job</a>
            </div>
        @endif
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="table-responsive">
                <table class="table display mb-4 dataTablesCard job-table table-responsive-xl card-table">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Job Title</th>
                        <th>Position</th>
                        <th>Type</th>
                        <th>Date Posted</th>
                        <th>Last Date To Apply</th>
                        <th>Company</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php($x = $jobs->firstItem())
                    @forelse($jobs as $job)
                        <tr>
                            <td>{{ $x++ }}</td>
                            <td>{{ $job->title }}</td>
                            <td>{{ $job->subtitle }}</td>
                            <td class="wspace-no">{{ $job->type }}</td>
                            <td>{{ \Carbon\Carbon::parse($job->post_date)->format('Y M d') }}</td>
                            <td>{{ \Carbon\Carbon::parse($job->expire_at)->format('Y M d') }}</td>
                            <td>{{ $job->company->name??'-- ? --' }}
                                <br><small>{{ $job->branch->location??'-- ? --' }}</small></td>
                            <td>
                                @if($job->active == 2)
                                    <span class="badge badge-warning badge-xs light text-dark">Pending Decision</span>
                                @elseif($job->active == 0)
                                    <span class="badge badge-warning badge-xs light text-dark">Closed</span>
                                @elseif(!null == $job->expire_at && \Carbon\Carbon::parse($job->expire_at)->isBefore(\Carbon\Carbon::now()))
                                    <span class="badge badge-danger badge-xs light text-dark"> Updated </span>
                                @else
                                    <span class="badge badge-success badge-xs light text-dark">Open</span>
                                @endif
                            </td>
                            <td>
                                <div class="action-buttons d-flex justify-content-end">
                                    <a href="{{ route('panel.job.show', $job->code) }}"
                                       class="btn btn-success btn-sm light mr-2" title="Details">
                                        <i class="fa fa-eye"></i>
                                    </a>
                                    @if(in_array(auth()->user()->type, ['admin', 'employer']))
                                        <a href="{{ route('panel.job.entity', $job->code) }}"
                                           class="btn btn-secondary btn-sm light mr-2" title="Modify"><i
                                                class="fa fa-pencil"></i></a>
                                        <a class="btn btn-danger btn-sm light" title="Delete" data-bs-toggle="modal"
                                           data-bs-target="#delete{{ $job->code }}"><i class="fa fa-trash"></i> </a>
                                    @endif
                                </div>
                            </td>
                        </tr>
                        <div class="modal fade" id="delete{{ $job->code }}">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    {{ html()->form('delete', route('panel.job.delete', $job->code))->open() }}
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete confirmation</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal">
                                        </button>
                                    </div>
                                    <div class="modal-body">Do you want to delete  <i
                                            class="text-info">{{ $job->title }}</i> permanently ? 
                                    </div>
                                    <div class="modal-footer">
                                        <div class="row" style="display: contents">
                                            <div class="col">
                                                {{ html()->button('Close')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                            </div>
                                            <div class="col text-end">
                                                {{ html()->submit('Delete')->class('btn btn-primary btn-sm') }}
                                            </div>
                                        </div>
                                    </div>
                                    {{ html()->form()->close() }}
                                </div>
                            </div>
                        </div>
                    @empty
                        <tr>
                            <td colspan="100%" class="text-center">
                                <p>Entries not found</p>
                                @if(in_array(auth()->user()->type, ['admin', 'employer']))
                                    To add to this list go
                                    to {{ html()->a(route('panel.job.entity'), 'Add new job')->class('badge badge-primary badge-sm') }}
                                    or {{ html()->a(route('panel.job.import'), 'Import form CSV')->class('badge badge-primary badge-sm') }}
                                    .
                                @endif
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr class="text-center">
                        <td colspan="100%">
                            {{ $jobs->withQueryString()->links() }}
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script') @endpush