routes/web.php
<?php

use App\Http\Controllers\AjaxController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CandidateController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PanelController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::controller(AuthController::class)->group(function () {
    Route::any('login/{socialite?}', 'login')->name('login');
    Route::any('auth/{platform}-callback', 'authCallback')->name('auth.callback')->whereIn('socialite', ['google', 'facebook']);
    Route::any('auth/{platform}', 'authCall')->name('auth')->whereIn('socialite', ['google', 'facebook']);
    Route::any('register{company?}', 'register')->name('register', "[\w'-]+");
    Route::any('register/branch', 'branchAssign')->name('branch.assign');
    Route::any('recover', 'recover')->name('recover');
    Route::any('verify/{code?}', 'verify')->name('verify');
    Route::any('logout', 'logout')->name('logout');
});

Route::name('panel.')->middleware('access')->group(function () {
    Route::controller(PanelController::class)->group(function(){
        Route::get('/', 'home')->name('home');
        Route::get('profile', 'profile')->name('profile');
        Route::any('profile/modify', 'profileModify')->name('profile.modify');
        Route::any('profile/change-password', 'changePassword')->name('profile.change-password');
        Route::any('profile/branch', 'myBranch')->name('profile.branch');
        Route::any('job-preference', 'jobPreference')->name('jop-preference');
        Route::any('setting', 'setting')->name('setting');
    });
    Route::prefix('job')->name('job.')->controller(JobController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('import', 'import')->name('import');
        Route::any('saved', 'saved')->name('saved');
        Route::any('applied', 'applied')->name('applied');
        Route::get('{code}/apply', 'apply')->name('apply');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
        Route::get('{code}', 'show')->name('show');
    });
    Route::prefix('category')->name('category.')->controller(CategoryController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
        Route::get('{code}', 'show')->name('show');
    });
    Route::prefix('employee')->name('company.')->controller(CompanyController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::any('branch/{code}', 'branch')->name('branch');
        Route::delete('branch/{code}/delete', 'branchDelete')->name('branch.delete');
        Route::any('invite/{code?}', 'invite')->name('invite');
        Route::delete('delete/{code}', 'destroy')->name('delete');
    });
    Route::prefix('candidate')->name('candidate.')->controller(CandidateController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
    });
});


Route::prefix('ajax')->name('ajax.')->middleware('access')->controller(AjaxController::class)->group(function () {
    Route::get('job/{code}/save', 'saveJob')->name('job.save');
    Route::get('job/{code}', 'jobInfo')->name('job');
    Route::get('country/{code}/branches', 'branches')->name('branches');
    Route::get('category/{code}/sub', 'categorySub')->name('subscategories');
});

Route::get('cmd/pa-{command}', function($command){
    try {
        \Illuminate\Support\Facades\Artisan::call($command);
    } catch (Exception $e){
        dump($e);
    }
    return redirect()->route('panel.dashboard')->with('success', 'Php artisan '.$command);
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory,SoftDeletes;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model['code'] = uniqid();
        });
    }

    public function scopeParentOnly($builder){
        return $builder->whereNull('parent_id');
    }

    public function children(){
        return $this->hasMany(Category::class, 'parent_id', 'id');
    }

    public function parent(){
        return $this->belongsTo(Category::class, 'parent_id', 'id');
    }

    public function jobs(){
        return $this->hasMany(Job::class, 'category_id', 'id');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\View;

class CategoryController extends Controller
{

    public function index(Request $request, $code = null)
    {
        if ($request->method() == 'POST') {

        } else {
            $parent = Category::where('code', $request->parent_id)->first();

            $categories = Category::query();
            if ($parent) {
                View::share('title', 'Sub Categories under ' . $parent->name);
                View::share('parentId', $parent->id);
                $categories->where('parent_id', $parent->id);
            } else {
                View::share('title', 'Job Categories');
                $categories->parentOnly();
            }
            $categories = $categories->paginate(20);
            return view('back.category.list', compact('categories'));
        }
    }

    public function entity(Request $request, $code = null)
    {

        $category = Category::where('code', $code)->first();

        if ($request->method() == 'POST' && !null == $code) {
            if (!$category)
                return back()->withErrors('Category information not found to update.');
            try {
                $category->update(['name' => $request->name]);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withErrors('Category failed to update.');
            }
            return redirect()->route('panel.category.list')->with('success', 'Category updated successfully.');
        } elseif ($request->method() == 'POST') {
            $request->validate([
                'name' => 'string|required'
            ]);

            $data['name'] = $request->name;
            if ($request->parentId)
                $data['parent_id'] = $request->parentId;

            try {
                Category::create($data);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withErrors('Category failed to update.');
            }
            return redirect()->route('panel.category.list')->with('success', 'Category updated successfully.');
        } elseif ($request->method() == 'DELETE' && $code) {

        } else {
            View::share('title', !null == $code ? 'Edit category' : 'Add new category');
            return view('back.category.form', compact('category'));
        }

    }

    public function destroy($code)
    {
        $category = Category::firstWhere('code', $code);
        if (!$category)
            return back()->withErrors('Category not found to delete. Reload page and try again.');
        try {
            $category->delete();
        } catch (\PDOException $e) {
            if (config('app.debug'))
                dd($e->getMessage());
            Log::error($e);
            return back()->withErrors('Category deletion failed.');
        }
        return back()->with('success', 'Category successfully deleted.');
    }
}

resources/views/back/category/branch.blade.php
@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4 flex-wrap">
        <h3 class="me-auto">{{ $title??'Location list' }}</h3>
        <div>
            <span role="button" data-bs-toggle="modal" data-bs-target="#addNew" class="btn btn-primary btn-xs me-3">
                <i class="fas fa-plus me-2"></i>Add New Location</span>
            <div class="modal fade" id="addNew">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        {{ html()->form('post', route('panel.company.branch', $company->code))->open() }}
                        <div class="modal-header">
                            <h5 class="modal-title">Add new location</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal">
                            </button>
                        </div>
                        <div class="modal-body">
                            {{ html()->label('New Location / Branch name', 'location')->class('form-label') }}
                            {{ html()->text('location')->class('form-control mb-3')->placeholder('Input new branch name')->required() }}
                        </div>
                        <div class="modal-footer">
                            <div class="row" style="display: contents">
                                <div class="col">
                                    {{ html()->button('Close')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                </div>
                                <div class="col text-end">
                                    {{ html()->submit('Add')->class('btn btn-primary btn-sm') }}
                                </div>
                            </div>
                        </div>
                        {{ html()->form()->close() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="table-responsive">
                <table class="table display mb-4 dataTablesCard location-table table-responsive-xl card-table"
                       id="example5">
                    <thead>
                    <tr>
                        <th style="white-space: nowrap; width: 1%">No</th>
                        <th>Location</th>
                        <th class="text-center">Jobs</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php($x = $branches->firstItem())
                    @forelse($branches as $branch)
                        <tr>
                            <td>{{ $x++ }}</td>
                            <td>{{ $branch->location }}</td>
                            <td class="text-center">
                                {{ html()->a(route('panel.job.list', ['branch_id' => $branch->id]), $branch->jobs->count())->target('blank')->class('badge badge-secondary badge-xs') }}</td>
                            <td>
                                @if($branch->user)
                                    <span class="badge badge-secondary badge-lg light"> User Linked </span>
                                @else
                                    <span class="badge badge-dark badge-lg light"> Not Linked</span>
                                @endif
                            </td>
                            <td style="white-space: nowrap; width: 5%">
                                <div class="action-buttons d-flex justify-content-end">
                                    <a href="{{ route('panel.company.entity', $branch->code) }}"
                                       class="btn btn-secondary btn-sm light mr-2" title="Modify" data-bs-toggle="modal"
                                       data-bs-target="#edit{{ $branch->code }}"><i
                                            class="fa fa-pencil"></i></a>
                                    <a class="btn btn-danger btn-sm light" title="Delete" data-bs-toggle="modal"
                                       data-bs-target="#delete{{ $branch->code }}"><i class="fa fa-trash"></i> </a>
                                </div>
                            </td>
                        </tr>

                    @empty
                        <tr>
                            <td colspan="100%" class="text-center">
                                <p>No Location exist here</p>
                                To add to this list go
                                to {{ html()->a(route('panel.company.entity'), 'Add new Location')->class('badge badge-primary badge-sm') }}
                                .
                                .
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr class="text-center">
                        <td colspan="100%">
                            {{ $branches->withQueryString()->links() }}
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
            @forelse($branches as $branch)
                <div class="modal fade" id="edit{{ $branch->code }}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            {{ html()->form('post', route('panel.company.branch', $company->code))->open() }}
                            {{ html()->hidden('branchCode', $branch->code) }}
                            <div class="modal-header">
                                <h5 class="modal-title">Modify location</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal">
                                </button>
                            </div>
                            <div class="modal-body">
                                {{ html()->label('New Location / Branch name', 'location')->class('form-label') }}
                                {{ html()->text('location', $branch->location)->class('form-control mb-3')->placeholder('Input new branch name')->required() }}
                            </div>
                            <div class="modal-footer">
                                <div class="row" style="display: contents">
                                    <div class="col">
                                        {{ html()->button('Close')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                    </div>
                                    <div class="col text-end">
                                        {{ html()->submit('Update')->class('btn btn-primary btn-sm') }}
                                    </div>
                                </div>
                            </div>
                            {{ html()->form()->close() }}
                        </div>
                    </div>
                </div>

                <div class="modal fade" id="delete{{ $branch->code }}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Delete confirmation</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <p class="m-0">
                                @if($branch->jobs->count())
                                    You can not delete this <i class="text-info">{{ $branch->location }}</i>
                                    location due to job reference. ? To delete need to remove alla reference job
                                    first.
                                @else
                                    Do you want to delete this <i class="text-info">{{ $branch->location }}</i>
                                    location permanently ? To agree press delete button otherwise cancel now.
                                @endif
                                </p>
                            </div>
                            <div class="modal-footer">
                                <div class="row" style="display: contents">
                                    <div class="col">
                                        {{ html()->button('Close')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                    </div>
                                    <div class="col text-end">
                                        @if($branch->jobs->count()??0)
                                            {{ html()->button('Delete !')->class('btn btn-dark  btn-sm')->type('button')->disabled() }}
                                        @else
                                            {{ html()->form('delete', route('panel.company.branch', $company->code))->open() }}
                                            {{ html()->hidden('branchCode', $branch->code) }}
                                            {{ html()->submit('Delete')->class('btn btn-primary btn-sm') }}
                                            {{ html()->form()->close() }}
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
        </div>
    </div>
@endsection

@push('script') @endpush

resources/views/back/category/form.blade.php
@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4">

    </div>
    <div class="row justify-content-center">
        <div class="col-sm-6 mb-3">
            <div class="card">
                @if($category??false)
                    {{ html()->form('POST', route('panel.category.entity', $category->code))->open() }}
                @else
                    {{ html()->form('POST', route('panel.category.entity'))->open() }}
                @endif

                <div class="card-header text-center">
                    <h4 class="mb-0 me-auto w-100">{{ $title??'Employer form' }}</h4>
                </div>

                <div class="card-body">
                    @if(request()->parentId??false)
                        {{ html()->hidden('parentId', request()->parentId) }}
                    @endif

                    {{ html()->label('Category Name', 'name')->class('form-label') }}
                    {{ html()->text('name', $category->name??null)->class('form-control mb-3')->placeholder('Input category name')->required()->autofocus() }}

                </div>
                <div class="card-footer">
                    <div class="row text-center">
                        <div class="col-sm-6">
                            {{ html()->reset('Reset')->class('btn btn-dark btn-sm') }}
                        </div>
                        <div class="col-sm-6">
                            {{ html()->submit('Submit')->class('btn btn-primary btn-sm') }}
                        </div>
                    </div>
                </div>
                {{ html()->form() }}
            </div>
        </div>
    </div>

@endsection

@push('script') @endpush

resources/views/back/category/list.blade.php
@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4 flex-wrap">
        <h3 class="me-auto">{{ $title??'Location list' }}</h3>
        <div>
            @if($parentId??false)
            <a href="{{ route('panel.category.entity', ['parentId' => $parentId]) }}" class="btn btn-primary btn-xs me-3">
                <i class="fas fa-plus me-2"></i>Add New SubCategory</a>
            @else
            <a href="{{ route('panel.category.entity') }}" class="btn btn-primary btn-xs me-3">
                <i class="fas fa-plus me-2"></i>Add New Category</a>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="table-responsive">
                <table class="table display mb-4 dataTablesCard location-table table-responsive-xl card-table"
                       id="example5">
                    <thead>
                    <tr>
                        <th style="white-space: nowrap; width: 1%">No</th>
                        <th>Name</th>
                        <th class="text-center">{{ ($parentId??false)?'Parent':'Sub' }} Categories</th>
                        <th class="text-center">Jobs</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php($x = $categories->firstItem())
                    @forelse($categories as $category)
                        <tr>
                            <td>{{ $x++ }}</td>
                            <td>{{ $category->name }}</td>
                            <td class="text-center">
                                @if($category->parent_id)
                                    {{ $category->parent->name }}
                                @else
                                    {{ html()->a(route('panel.category.list', ['parent_id' => $category->code]), $category->children->count()??0)->class('badge badge-secondary badge-xs') }}
                                @endif
                            </td>
                            <td class="text-center">
                                {{ html()->a(route('panel.job.list', ['category_id' => $category->id]), $category->jobs->count())->target('blank')->class('badge badge-secondary badge-xs') }}
                            </td>
                            <td style="white-space: nowrap; width: 5%">
                                <div class="action-buttons d-flex justify-content-end">
                                    <a href="{{ route('panel.category.entity', $category->code) }}"
                                       class="btn btn-secondary btn-sm light mr-2" title="Modify">
                                        <i class="fa fa-pencil"></i>
                                    </a>
                                    <a class="btn btn-danger btn-sm light" title="Delete" data-bs-toggle="modal"
                                       data-bs-target="#delete{{ $category->code }}"><i class="fa fa-trash"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>

                    @empty
                        <tr>
                            <td colspan="100%" class="text-center">
                                <p>Entires not found</p> 
                                @if($parentId??false)
                                    {{ html()->a(route('panel.category.entity', ['parentId' => $parentId]), '<i class="fas fa-plus me-2"></i> Add new SubCategory')->class('badge badge-primary badge-sm') }}
                                @else
                                    {{ html()->a(route('panel.category.entity'), '<i class="fas fa-plus me-2"></i> Add new Category')->class('badge badge-primary badge-sm') }}
                                @endif
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr class="text-center">
                        <td colspan="100%">
                            {{ $categories->withQueryString()->links() }}
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
            @forelse($categories as $category)
                @php($refference = ($category->jobs->count() || $category->children->count())?1:0)
                <div class="modal fade" id="delete{{ $category->code }}">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Delete confirmation</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                            </div>
                            <div class="modal-body">
                                <p class="m-0">
                                    @if($refference)
                                        You can not delete <i class="text-info">{{ $category->name }}</i>
                                        
                                    @else
                                        Do you want to delete  <i class="text-info">{{ $category->location }}</i>
                                         permanently ?
                                    @endif
                                </p>
                            </div>
                            <div class="modal-footer">
                                <div class="row" style="display: contents">
                                    <div class="col">
                                        {{ html()->button('Close')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                    </div>
                                    <div class="col text-end">
                                        @if($refference)
                                            {{ html()->button('Delete !')->class('btn btn-dark  btn-sm')->type('button')->disabled() }}
                                        @else
                                            {{ html()->form('delete', route('panel.category.delete', $category->code))->open() }}
                                            {{ html()->submit('Delete')->class('btn btn-primary btn-sm') }}
                                            {{ html()->form()->close() }}
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                @endforeach
        </div>
    </div>
@endsection

@push('script') @endpush