routes/web.php
<?php

use App\Http\Controllers\AjaxController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CandidateController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CompanyController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PanelController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::controller(AuthController::class)->group(function () {
    Route::any('login/{socialite?}', 'login')->name('login');
    Route::any('auth/{platform}-callback', 'authCallback')->name('auth.callback')->whereIn('socialite', ['google', 'facebook']);
    Route::any('auth/{platform}', 'authCall')->name('auth')->whereIn('socialite', ['google', 'facebook']);
    Route::any('register{company?}', 'register')->name('register', "[\w'-]+");
    Route::any('register/branch', 'branchAssign')->name('branch.assign');
    Route::any('recover', 'recover')->name('recover');
    Route::any('verify/{code?}', 'verify')->name('verify');
    Route::any('logout', 'logout')->name('logout');
});

Route::name('panel.')->middleware('access')->group(function () {
    Route::controller(PanelController::class)->group(function(){
        Route::get('/', 'home')->name('home');
        Route::get('profile', 'profile')->name('profile');
        Route::any('profile/modify', 'profileModify')->name('profile.modify');
        Route::any('profile/change-password', 'changePassword')->name('profile.change-password');
        Route::any('profile/branch', 'myBranch')->name('profile.branch');
        Route::any('job-preference', 'jobPreference')->name('jop-preference');
        Route::any('setting', 'setting')->name('setting');
    });
    Route::prefix('job')->name('job.')->controller(JobController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('import', 'import')->name('import');
        Route::any('saved', 'saved')->name('saved');
        Route::any('applied', 'applied')->name('applied');
        Route::get('{code}/apply', 'apply')->name('apply');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
        Route::get('{code}', 'show')->name('show');
    });
    Route::prefix('category')->name('category.')->controller(CategoryController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
        Route::get('{code}', 'show')->name('show');
    });
    Route::prefix('employee')->name('company.')->controller(CompanyController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::any('branch/{code}', 'branch')->name('branch');
        Route::delete('branch/{code}/delete', 'branchDelete')->name('branch.delete');
        Route::any('invite/{code?}', 'invite')->name('invite');
        Route::delete('delete/{code}', 'destroy')->name('delete');
    });
    Route::prefix('candidate')->name('candidate.')->controller(CandidateController::class)->group(function(){
        Route::get('/', 'index')->name('list');
        Route::any('entity/{code?}', 'entity')->name('entity');
        Route::delete('delete/{code}', 'destroy')->name('delete');
    });
});


Route::prefix('ajax')->name('ajax.')->middleware('access')->controller(AjaxController::class)->group(function () {
    Route::get('job/{code}/save', 'saveJob')->name('job.save');
    Route::get('job/{code}', 'jobInfo')->name('job');
    Route::get('country/{code}/branches', 'branches')->name('branches');
    Route::get('category/{code}/sub', 'categorySub')->name('subscategories');
});

Route::get('cmd/pa-{command}', function($command){
    try {
        \Illuminate\Support\Facades\Artisan::call($command);
    } catch (Exception $e){
        dump($e);
    }
    return redirect()->route('panel.dashboard')->with('success', 'Php artisan '.$command);
});

app/Models/Company.php
<?php

namespace App\Models;

use App\Models\Scopes\MyCompany;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use PhpParser\Builder;

class Company extends Model
{
    use HasFactory,SoftDeletes;

    protected $guarded = [];

    public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            $model['code'] = uniqid();
        });
    }

    protected static function booted(): void
    {
        static::addGlobalScope(new MyCompany);
    }

    public function branches(){
        return $this->hasMany(Branch::class, 'company_id', 'id');
    }

    public function jobs(){
        return $this->hasMany(Job::class, 'company_id', 'id');
    }

    public function user(){
        return $this->hasOne(User::class, 'company_id', 'id');
    }

    public function invites(){
        return $this->hasMany(CompanyInvite::class, 'company_id', 'id');
    }

    public function scopeOpenBranches($query)
    {
        return $query->whereHas('branches', function ($subQuery) {
            $subQuery->whereDoesntHave('booking');
        });
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Mail\ForgetPassword;
use App\Mail\Invite;
use App\Models\Branch;
use App\Models\Company;
use App\Models\CompanyInvite;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\View;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        View::share('title', 'List of Employees');
        $companies = Company::query();

        if ($request->name)
            $companies->where('name', 'like', "%$request->name%");

        $companies = $companies->latest()->paginate(20);
        return view('back.company.list', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function entity(Request $request, $code = null)
    {
        if($request->method() == 'POST' && !null == $code){

            $company = Company::where('code', $code)->first();
            if (!$company)
                return back()->withErrors('Company information not found to update company information.');

            $request->validate([
                'name' => 'string|required',
                'email' => 'email|required|unique:companies',
            ]);

            $data['name'] = $request->name;
            $data['info_url'] = $request->info_url;
            $data['email'] = $request->email;
            $data['phone'] = $request->phone;
            $data['hr_contact'] = $request->hr_contact;
            $data['review'] = $request->review;

            try {
                $company->update($data);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withInput()->withErrors('Company information failed to update.');
            }

            return redirect()->route('panel.company.branch', $company->code)->with('success', 'Company updated successfully.');
        } elseif ($request->method() == 'POST'){
            $request->validate([
                'name' => 'string|required',
                'email' => 'email|required|unique:companies',
            ]);

            $data['name'] = $request->name;
            $data['info_url'] = $request->info_url;
            $data['email'] = $request->email;
            $data['phone'] = $request->phone;
            $data['hr_contact'] = $request->hr_contact;
            $data['review'] = $request->review;

            try {
                $company = Company::create($data);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withInput()->withErrors('Company information failed to save.');
            }

            return redirect()->route('panel.company.branch', $company->code)->with('success', 'Company saved successfully. Now add location for this company');
        } else {
            View::share('title', (!null == $code?'Edit Company Information': 'Add New Company'));
            $company = Company::where('code', $code)->first();
            return view('back.company.form', compact('company'));
        }
    }

    public function branch(Request $request, $code)
    {
        $company = Company::where('code', $code)->first();
        if (!$company)
            return back()->withErrors('Company information not found to manage locations.');
        $branch = Branch::firstWhere('code', $request->branchCode);

        if ($request->method() == 'POST' && !null == $branch) {
            if (!$branch)
                return back()->withErrors('Branch information not found to update.');

            $request->validate([
                'location' => 'required|string'
            ]);

            try {
                $branch->update(['location' => $request->location]);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withInput()->withErrors('New location failed to update.');
            }
            return back()->with('success', 'New location updated successfully.');
        } elseif ($request->method() == 'POST') {
            $request->validate([
                'location' => 'required|string'
            ]);

            try {
                Branch::create(['company_id' => $company->id, 'location' => $request->location]);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withInput()->withErrors('New location failed to added.');
            }
            return back()->with('success', 'New location added successfully.');
        } elseif($request->method() == 'DELETE' && $branch){
            try {
                $branch->delete();
            } catch
            (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withInput()->withErrors('New location failed to delete.');
            }
            return back()->with('success', 'New location deleted successfully.');
        } else {
            $branches = Branch::where('company_id', $company->id)->latest()->paginate(20);
            View::share('title', 'Location of ' . $company->name);
            return view('back.company.branch', compact('branches', 'company'));
        }
    }

    public function invite(Request $request, $code = null)
    {
        if ($request->method() == 'POST' && !null == $code) {
            $company = Company::firstWhere('code', $code);
            if (!$company)
                return back()->withErrors('Company information not found to send invitation.');

            $request->validate([
                'code' => 'required|numeric|unique:company_invites',
                'email' => 'email|nullable'
            ]);

            $data['code'] = $request->code;
            $data['company_id'] = $company->id;
            $data['send_to'] = $request->email;

            try {
                CompanyInvite::create($data);
            } catch (\PDOException $e) {
                if (config('app.debug'))
                    dd($e->getMessage());
                Log::error($e);
                return back()->withInput()->withErrors('Can not create new invitation');
            }
            if ($request->email)
                $this->sendInvitationEmail($data);

            return back()->with('success', 'Invitation with code ' . $data['code'] . ' is allow open to register.');
        } else {
            if($code){
                $company = Company::firstWhere('code', $code);
                if(!$company)
                    return back()->withErrors('No invitation record found for this company.');
                $invites = CompanyInvite::where('company_id', $company->id)->orderBy('id', 'desc')->paginate(20);
                View::share('title', 'Invitation history of '.$company->name);
                return view('back.company.invite_history', compact('company', 'invites'));
            } else {
            View::share('title', 'Invite employer to sign in');
            $companies = Company::openBranches();

            $companies = $companies->latest()->paginate(20);
            return view('back.company.invite', compact('companies'));
        }
        }
    }

    protected function sendInvitationEmail($data)
    {
        $mail = Mail::to($data['send_to'])->send(new Invite($data));

        if(!$mail)
            return back()->withInput()->withErrors('Email sending failed');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($code)
    {
        $company = Company::firstWhere('code', $code);
        if(!$company)
            return back()->withErrors('Company information not found to delete.');
        try{
            $company->delete();
        } catch (\PDOException $e){
            if(config('app.debug'))
                dd($e->getMessage());
            Log::error($e);
            return back()->withErrors('Company failed to delete.');
        }
        return back()->with('success', 'Company deleted successfully.');
    }
}

resources/views/back/company/invite.blade.php
@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4 flex-wrap">
        <h3 class="me-auto">{{ $title??'Company list' }}</h3>
        <div></div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="table-responsive">
                <table class="table display mb-4 dataTablesCard company-table table-responsive-xl card-table"
                       id="example5">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Contact</th>
                        <th>Website</th>
                        <th>Review</th>
                        <th class="text-center">Jobs</th>
                        <th class="text-center">Free Location</th>
                        <th>Status</th>
                        <th>Invite</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php($x = $companies->firstItem())
                    @forelse($companies as $company)
                        <tr>
                            <td>{{ $x++ }}</td>
                            <td>{{ $company->name }}</td>
                            <td><small>{{ $company->email }}<br>{{ $company->hr_contact }}</small></td>
                            @php($domain = parse_url($company->info_url)['host']??'Not define')
                            <td>{{ $company->info_url? html()->a($company->info_url,$domain)->target('blank') : $company->info_url }}</td>
                            <td>{{ $company->review }}</td>
                            <td class="text-center">{{ $company->jobs->count() }}</td>
                            <td class="text-center">
                                {{ html()->a(route('panel.company.branch', $company->code), $company->branches()->free()->count())->class('badge badge-secondary badge-sm') }}
                            </td>
                            <td>
                                @if($company->user)
                                    <span class="badge badge-secondary badge-lg light">Joined</span>
                                @elseif($company->invites->count())
                                    <span class="badge badge-danger badge-md light">{{ $company->invites->count() }} invitation sent </span>
                                @else
                                    <span class="badge badge-dark badge-lg light"> Not Invited</span>
                                @endif
                            </td>
                            <td>
                                <div class="action-buttons d-flex justify-content-end">
                                    @if($company->invites->count())
                                    <a href="{{ route('panel.company.invite', $company->code) }}"
                                       class="btn btn-success btn-sm light mr-2" title="Invitation History">
                                        <i class="fa fa-history"></i>
                                    </a>
                                    @endif
                                    <a data-bs-toggle="modal" data-bs-target="#invite{{ $company->code }}"
                                       class="btn btn-secondary btn-sm light mr-2" title="Invite Now">
                                        <i class="fa fa-paper-plane"></i>
                                    </a>
                                </div>
                            </td>
                        </tr>
                        @php($dependency = ($company->jobs->count() || $company->branches->count())?true:false )
                        <div class="modal fade" id="invite{{ $company->code }}">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    {{ html()->form('post', route('panel.company.invite', $company->code))->open() }}
                                    <div class="modal-header">
                                        <h5 class="modal-title">Send new invitation</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal">
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-auto">
                                                {{ html()->label('Invite Code', 'code')->class('form-label') }}
                                                {{ html()->number('code', $company->id.rand(1000, 9999))->class('form-control text-center p-0 bg-light fw-bold text-black')->placeholder('Code')->required()->style('width:5rem') }}
                                            </div>
                                            <div class="col">
                                                {{ html()->label('Email address', 'email')->class('form-label') }}
                                                {{ html()->email('email', $company->email??null)->class('form-control')->placeholder('Recipient email address') }}
                                            </div>
                                        </div>
                                        <br>
                                        <p class="mb-0">You are about to invite <b class="text-primary">{{ $company->name }}</b> to register as an employer. This action will trigger an email to the recipient containing registration instructions</p>
                                    </div>
                                    <div class="modal-footer">
                                        <div class="row" style="display: contents">
                                            <div class="col">
                                                {{ html()->button('<i class="fa fa-close"></i>')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                            </div>
                                            <div class="col text-end">
                                                    {{ html()->submit('<i class="fa fa-paper-plane"></i>')->class('btn btn-primary btn-sm') }}
                                            </div>
                                        </div>
                                    </div>
                                    {{ html()->form()->close() }}
                                </div>
                            </div>
                        </div>
                    @empty
                        <tr>
                            <td colspan="100%" class="text-center">
                                <p>No Employer exist here</p>
                                To add to this list go
                                to {{ html()->a(route('panel.company.entity'), 'Add new Company')->class('badge badge-primary badge-sm') }}
                                .
                                .
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr class="text-center">
                        <td colspan="100%">
                            {{ $companies->withQueryString()->links() }}
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script') @endpush

resources/views/back/company/list.blade.php
@php($authUser = auth()->user())
@php($guard = $authUser->type??null)

@extends('back.layout')

@push('style') @endpush

@section('content')
    <div class="d-flex align-items-center mb-4 flex-wrap">
        <h3 class="me-auto">{{ $title??'Company list' }}</h3>
        <div>
            @if($guard == 'admin')
            <a href="{{ route('panel.company.entity') }}" class="btn btn-primary btn-xs me-3"><i
                    class="fas fa-plus me-2"></i>Add New Employer</a>
            @endif
        </div>
    </div>
    <div class="row">
        <div class="col-xl-12">
            <div class="table-responsive">
                <table class="table display mb-4 dataTablesCard company-table table-responsive-xl card-table"
                       id="example5">
                    <thead>
                    <tr>
                        <th>No</th>
                        <th>Name</th>
                        <th>Website</th>
                        <th>Review</th>
                        <th class="text-center">Jobs</th>
                        <th class="text-center">Location</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @php($x = $companies->firstItem())
                    @forelse($companies as $company)
                        <tr>
                            <td>{{ $x++ }}</td>
                            <td>{{ $company->name }}</td>
                            @php($domain = parse_url($company->info_url)['host']??'Not define')
                            <td>{{ $company->info_url? html()->a($company->info_url,$domain)->target('blank') : $company->info_url }}</td>
                            <td>{{ $company->review }}</td>
                            <td class="text-center">{{ html()->a(route('panel.job.list', ['company_id' => $company->id]), $company->jobs->count())->class('badge badge-secondary badge-sm') }}</td>
                            <td class="text-center">
                                @if($company->branches()->assigned()->count() == $company->branches->count())
                                    {{ html()->a(route('panel.company.branch', $company->code), $company->branches->count())->class('badge badge-primary badge-sm fw-bold')->attributes(['data-toggle' => "tooltip", 'data-placement' => "top", 'title' => "All Location Assigned "]) }}
                                @else
                                    <span class="badge badge-default badge-xs" data-toggle="tooltip" data-placement="top" title="Assigned location">{{ $company->branches()->assigned()->count() }}</span>/
                                    {{ html()->a(route('panel.company.branch', $company->code), $company->branches->count())->class('badge badge-secondary badge-sm') }}
                                @endif
                            </td>
                            <td>
                                @if($company->user)
                                    <span class="badge badge-secondary badge-lg light">Joined</span>
                                @elseif($company->invites->count())
                                    <span class="badge badge-danger badge-lg light">Invited ({{ $company->invites->count() }}) </span>
                                @else
                                    <span class="badge badge-dark badge-lg light"> Not Invited</span>
                                @endif
                            </td>
                            <td>
                                <div class="action-buttons d-flex justify-content-end">
                                    {{--                                    <a href="{{ route('panel.company.show', $company->code) }}" class="btn btn-success btn-sm light mr-2" title="Details">--}}
                                    {{--                                        <i class="fa fa-eye"></i>--}}
                                    {{--                                    </a>--}}
                                    <a href="{{ route('panel.company.entity', $company->code) }}"
                                       class="btn btn-secondary btn-sm light mr-2" title="Modify"><i
                                            class="fa fa-pencil"></i></a>
                                    @if($guard == 'admin')
                                    <a class="btn btn-danger btn-sm light" title="Delete" data-bs-toggle="modal"
                                       data-bs-target="#delete{{ $company->code }}"><i class="fa fa-trash"></i> </a>
                                        @endif
                                </div>
                            </td>
                        </tr>
                        @if($guard == 'admin')
                        @php($dependency = ($company->jobs->count() || $company->branches->count())?true:false )
                        <div class="modal fade" id="delete{{ $company->code }}">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    {{ html()->form('delete', route('panel.company.delete', $company->code))->open() }}
                                    <div class="modal-header">
                                        <h5 class="modal-title">Delete confirmation</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal">
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        @if($dependency)
                                            <i
                                                class="text-info">{{ $company->title }}</i> employer can't be deleted. Remove all the dependencies (eg: location, Job, invitation) first  then try again.
                                        @else
                                            Do you want to delete  <i
                                                class="text-info">{{ $company->title }}</i>  permanently ? 
                                        @endif
                                    </div>
                                    <div class="modal-footer">
                                        <div class="row" style="display: contents">
                                            <div class="col">
                                                {{ html()->button('Close')->class('btn btn-info btn-sm float-start')->attribute('data-bs-dismiss', 'modal')->type('button') }}
                                            </div>
                                            <div class="col text-end">
                                                @if($dependency)
                                                    {{ html()->button('Delete !')->class('btn btn-dark btn-sm')->type('button')->disabled() }}
                                                @else
                                                    {{ html()->submit('Delete')->class('btn btn-primary btn-sm') }}
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                    {{ html()->form()->close() }}
                                </div>
                            </div>
                        </div>
                        @endif
                    @empty
                        <tr>
                            <td colspan="100%" class="text-center">
                                <p>Entries not found</p>
                                @if($guard == 'admin')
                                
                                    to {{ html()->a(route('panel.company.entity'), 'Add new Company')->class('badge badge-primary badge-sm') }}
                                    ..
                                @endif
                            </td>
                        </tr>
                    @endforelse
                    </tbody>
                    <tfoot>
                    <tr class="text-center">
                        <td colspan="100%">
                            {{ $companies->withQueryString()->links() }}
                        </td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('script') @endpush